title: 'Fugazzeta Soft'
description: 'Another web page on the internet'
author: 'Martín E. Zahnd'
developer: 'Martín E. Zahnd'
# Base hostname and protocol
url: "https://fugazzeta-soft.000webhostapp.com/" 

logo-path: '/res/logo.png'

exclude: [
    private/,
    sass/,
    .gitignore,
    build.sh,
    run_server.sh
  ]

markdown: kramdown
highlighter: rouge
kramdown:
  #  input: kramdown
  input: GFM
  syntax_highlighter_opts:
    default_lang: plain
    guess_lang: true
    line_numbers: true
    #
    # From https://github.com/rouge-ruby/rouge#configuration
    start_line: 1 # the number of the first row
    line_id: 'line-%i' # a sprintf template for id attribute with current line number
    line_class: 'lineno' # a CSS class for each table-row
    table_class: 'rouge-line-table' # a CSS class for the table
    gutter_class: 'rouge-gutter' # a CSS class for the line-number cell
    code_class: 'rouge-code' # a CSS class for the code cell

excerpt_separator: <!--more-->

permalink: /:collection/:year/:month/:day/:title:output_ext
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title:output_ext

  notes:
    output: true
    permalink: /notes/:title:output_ext

katex:
  # Path used to search for katex.min.js
  # js_path: "{{ Gem::lib_path }}/js"
  rendering_options:
    # Default KaTeX rendering options. 
    # See https://github.com/Khan/KaTeX#rendering-options
    # throwOnError - set to false if you want rendering to output error as 
    # text rather than a build error
    throw_error: true         
    error_color: "#cc0000"

toc:
  # See https://github.com/toshimaru/jekyll-toc#customization
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

plugins:
    # KaTeX equations
  - jekyll-katex
    # Table of Contents
  - jekyll-toc
    # Adds loading="lazy" to images and iframe
    # https://github.com/gildesmarais/jekyll-loading-lazy
  - jekyll-loading-lazy
  - jekyll-sitemap  # Run last !
